export const LIMIT=5

export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST'
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_FAILURE = 'GET_STUDENT_FAILURE'


export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE'

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE'

export const UPDATE_REQUEST = 'UPDATE_REQUEST'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAILURE = 'UPDATE_FAILURE'

export const SEARCH_STUDENT_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_STUDENT_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_STUDENT_FAILURE = 'SEARCH_FAILURE'

export const PAGINATE_STUDENT_REQUEST = 'PAGINATE_STUDENT_REQUEST'
export const PAGINATE_STUDENT_SUCCESS = 'PAGINATE_STUDENT_SUCCESS'
export const PAGINATE_STUDENT_FAILURE = 'PAGINATE_STUDENT_FAILURE'